spring:
  application:
    name: enrollstat

  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: public


  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

  devtools:
    add-properties: false

  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    web: INFO
    enrollstat: INFO